name: Build

on: [workflow_dispatch]

env:
  app_file: LibreWolf-WinUpdater

jobs:
  build:
    runs-on: codeberg-small
    container:
      image: scottyhardy/docker-wine:stable
    steps:
      - name: Set up dependencies
        run: |
          wget https://pkg.ossign.org/debian/repository.key -O /etc/apt/keyrings/ossign.asc -q
          echo "deb [signed-by=/etc/apt/keyrings/ossign.asc] https://pkg.ossign.org/debian all main" | tee /etc/apt/sources.list.d/ossign.list
          sudo apt-get update
          sudo apt-get install -y nodejs zip ossign

      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Ahk2Exe
        run: |
          wget -qO ahk.zip https://github.com/AutoHotkey/AutoHotkey/releases/download/v1.1.37.02/AutoHotkey_1.1.37.02.zip
          echo "6f3663f7cdd25063c8c8728f5d9b07813ced8780522fd1f124ba539e2854215f ahk.zip" | sha256sum -c || exit 1
          unzip -j ahk.zip Compiler/Ahk2Exe.exe "Compiler/Unicode 32-bit.bin"
          rm ahk.zip

      - name: Set up BinMod
        run: |
          xvfb-run wine Ahk2Exe.exe /silent verbose /base "Unicode 32-bit.bin" /in BinMod.ahk

      - name: Set up Resource Hacker
        run: |
          wget -qO rh.zip https://www.angusj.com/resourcehacker/resource_hacker.zip
          unzip rh.zip ResourceHacker.exe
          echo "14a44fe31b04fbcc65e94e80016138a2e9fc9bb6dfcea09b98de57f8a22a1240 ResourceHacker.exe" | sha256sum -c || exit 1
          rm rh.zip

      - name: Build executable
        run: |
          xvfb-run wine Ahk2Exe.exe /silent verbose /in ${{ env.APP_FILE }}.ahk
          sed -i.bak -b -e s/AutoHotkey/WinUpdater/gI -e s/A.u.t.o.H.o.t.k.e.y/W.i.n.U.p.d.a.t.e.r/gI LibreWolf-WinUpdater.exe
          rm *.bak

      - name: Sign executable with OSSign
        if: ${{ secrets.OSSIGN_CONFIG != '' }}
        env:
          OSSIGN_CONFIG: ${{ secrets.OSSIGN_CONFIG }}
        run: |
          ossign -t pecoff -o ${{ env.APP_FILE }}.exe ${{ env.APP_FILE }}.exe

      - id: virustotal
        if: ${{ secrets.VT_API_KEY != '' }}
        name: Scan with VirusTotal
        uses: https://github.com/crazy-max/ghaction-virustotal@v5
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./${{ env.APP_FILE }}.exe

      - name: Create zip
        run: |
          APP_VERSION=$(grep -oP "SetFileVersion \K[\d.]+" ${{ env.APP_FILE }}.ahk)
          mkdir ./dist
          zip ./dist/${{ env.APP_FILE }}_${APP_VERSION}.zip ${{ env.APP_FILE }}.exe ${{ env.APP_FILE }}.url *.ps1

      - name: Upload artifacts
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          path: |
            dist/${{ env.APP_FILE }}*.zip
          retention-days: 7
